### ISSUE TITLE
i face on error when extend dataset class. How extend to other dataset like voc?

### ISSUE THREAD

**Issue by EzoBear** [victoresque/pytorch-template#46]
I change one line two case in data loader. 
first case:
Before
self.dataset = datasets.MNIST(self.data_dir, train=training, download=True, transform=trsfm)
After
self.dataset = datasets.MNIST(self.data_dir, train=training, download=True, transform=trsfm, target_transform=trsfm)
second case:
Before
origin code
After
self.dataset = datasets.VOCDetection(self.data_dir, year='2012', image_set='trainval', download=True, transform=trsfm, target_transform=trsfm)

but i have been facing on similar error on 2 case.

![image](https://user-images.githubusercontent.com/35482870/56082523-ae892c80-5e54-11e9-8ed6-c56a0da15418.png)

may be my think is can't convert  data loader as enumerate variance...
![image](https://user-images.githubusercontent.com/35482870/56082544-fa3bd600-5e54-11e9-83d6-471f7f36142c.png)

i wonder my guess is right and how extends mnist data loader code to voc dataloader?

**Comment by SunQpark** [comment]
transforms of torchvision are only for images, but you are using it also on target.
So, remove `, target_transform=trsfm` part.

**Comment by EzoBear** [comment]
data loader have been extended to available to using target transform.
![image](https://user-images.githubusercontent.com/35482870/56124394-82cf8900-5fb1-11e9-9cfa-274773b3028d.png)
return value of dataloader's get item is image,target. target is [cls_name,[xmin, ymin, xmax, ymax]]
but i face on other error.
![image](https://user-images.githubusercontent.com/35482870/56125597-3df92180-5fb4-11e9-8150-b51db8c286c5.png)
i think mnist data is gary but voc data is rgb image. so first rank is not same. 
mnist is [1,x,y] but voc is [3,x,y]
where should i look??

**Comment by SunQpark** [comment]
Since dataset only returns single image and target, `data_loader` calls `collate` internally to stack them together into a batch. For mnist, image from dataset has size (1, 28, 28) and default functions stacks n images to make (n, 1, 28, 28) batch.  But for VOC images have variable shape(3, ?, ?) so you should resize or crop images into same size(use `transforms.Resize(224)`, for example). 

But sadly, this is not your last error to encounter, since targets also have various size in detection task. All I can say is that you will need to use `collate_fn` argument to fix that. You'd netter ask Google or Stackoverflow how to do that.
